title: M A ZUHA | GitHub Profile Page!
logo: /assets/img/logo.png
description: Welcome to M A Zuha GitHub Profile Site! This site is used Minimal Jekyll theme for GitHub Pages. Help us make these docs or pages great! 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
